inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'app/views/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
